version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/fw-agent"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/fw-control"
    schedule:
      interval: "weekly"
